# Generated by Django 3.2.9 on 2022-05-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_alter_account_verify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_verify',
            name='user',
        ),
    ]
