# Generated by Django 3.2.9 on 2022-05-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_remove_account_verify_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account_verify',
        ),
    ]
