# Generated by Django 3.2.9 on 2022-04-28 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_auto_20220428_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
