# Generated by Django 3.2.9 on 2022-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_laptop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='description',
            field=models.TextField(max_length=2050),
        ),
    ]
