# Generated by Django 3.2.9 on 2022-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0004_alter_laptop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
