# Generated by Django 3.2.9 on 2022-04-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0009_rename_items_order_newitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
