# Generated by Django 3.2.9 on 2022-05-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0016_auto_20220428_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
